rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - ruby-head
 - ree
 - jruby
 - rbx
 - rbx-2.0
before_script:
 - 'sh -e /etc/init.d/xvfb start'
before_install:
 - 'git submodule update --init'
env:
  - DISPLAY=':99.0'
